query CrossProductAccountDetails($userId: ID!) {
  accountsByUserId(userId: $userId) {
    accountOwners {
      accountNickname
      __typename
    }
    branch
    currency
    id
    type
    __typename
  }
}
