export default {
    fetchSecurity: 'FetchSecurity',
    autoInvestQuery: 'AutoInvestQuery',
    cashAccountBalance: 'CashAccountBalance',
    cashClientDashboard: 'CashClientDashboard',
    clientSessionsQuery: 'clientSessionsQuery',
    crossProductAccountDetails: 'CrossProductAccountDetails',
    fetchClientInterestRate: 'FetchClientInterestRate',
    fetchCryptoNews: 'fetchCryptoNews',
    fetchCryptoSpread: 'fetchCryptoSpread',
    fetchFullProgressiveIdv: 'fetchFullProgressiveIdv',
    fetchIdentityAccounts: 'FetchIdentityAccounts',
    fetchSecurityHistoricalQuotes: 'FetchSecurityHistoricalQuotes',
    fetchSecurityNews: 'fetchSecurityNews',
    fetchWatchlist: 'FetchWatchlist',
    getPortfolioValue: 'getPortfolioValue',
    identityHistoricalFinancialsQuery: 'IdentityHistoricalFinancialsQuery',
    listActivitiesForAccount: 'ListActivitiesForAccount',
    listDepositsForAccount: 'ListDepositsForAccount',
    listPendingInternalTransfersForAccount: 'ListPendingInternalTransfersForAccount',
    listWithdrawalsForAccount: 'ListWithdrawalsForAccount',
    payments: 'Payments',
    personQuery: 'personQuery',
    referralsv2Query: 'Referralsv2Query',
    searchFundingIntentsQuery: 'SearchFundingIntentsQuery',
    spendTransactions: 'SpendTransactions'
}
